Update patch set 2
Patch Set 2:

Error report full
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.IllegalArgumentException: Failed to find storage device at /storage/sdcard1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2356)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2418)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.IllegalArgumentException: Failed to find storage device at /storage/sdcard1
	at android.os.Environment.isExternalStorageRemovable(Environment.java:831)
	at com.android.settings.MasterClear.establishInitialState(MasterClear.java:183)
	at com.android.settings.MasterClear.onCreateView(MasterClear.java:225)
	at android.app.Fragment.performCreateView(Fragment.java:2053)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
	at android.app.Activity.performCreateCommon(Activity.java:5985)
	at android.app.Activity.performCreate(Activity.java:5992)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2309)
	... 10 more

Patch-set: 2